color: red
fieldLayouts:
  9520b4da-7f17-4d5d-8850-e273184cc180:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-22T08:16:20+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: listItem
            includeInCards: false
            instructions: null
            label: 'List Item'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5dfc647-1353-40ac-9712-3b248f683ac0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8bf0facd-cc1a-4d2e-a8a8-02118c95d289
        userCondition: null
handle: listItem
hasTitleField: false
icon: ballot-check
name: 'List Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
