color: blue
fieldLayouts:
  318f5cfe-5bbb-4fee-a56d-6e8b7e0011a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T09:58:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0cb7acec-6347-4c57-bfc3-57820a301a7e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:59:53+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: SubText
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3282956a-5bca-4171-b340-a31b3b9016ed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a6ef2dc-9808-4b8e-9607-638bd4663b43
        userCondition: null
handle: locations
hasTitleField: true
icon: alien
name: Locations
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
