defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1739068c-3a36-4d7f-bc10-1d6f24261680 # Categories
handle: categories
maxAuthors: 1
name: Categories
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: true
    template: categories/_entry.twig
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: a97f3558-bce2-422e-a2f5-6842c2e296e6
type: structure
